In [2]:
import requests
import pandas as pd
import sqlite3

In [3]:
server = "https://services-eu1.arcgis.com/kswen6BYexuc1SUk/arcgis/rest/services/BathingWatersDirectiveProtectedAreas/FeatureServer/0/query?where=1%3D1&outFields=Name,PA_CD,centroidX,centroidY&returnGeometry=false&outSR=4326&f=json"

In [4]:
data = requests.get(server, headers={"Accept": "application/json, text/javascript, */*; q=0.01"})

In [7]:
df = pd.json_normalize(data.json()['features'])
df = df.rename(columns={
    "attributes.PA_CD": "id",
    "attributes.Name": "name",
    "attributes.centroidX": "long",
    "attributes.centroidY": "lat"
})\
.set_index("id")\
# .drop(columns=[
#     'attributes.CLASS_DESCRIPTION', 'attributes.BW_URL',
#     'attributes.YEAR'
# ])
df['name'] = df['name'].str.title()
df['alternate_name'] = df['name']
locations = df[[
    'name', 'alternate_name', 'lat', 'long'
]].copy()
locations

,name,alternate_name,lat,long
id,,,,
UKGBNIPA3_20021,Portballintrae Salmon Rock,Portballintrae Salmon Rock,55.220361,-6.543778
UKGBNIPA3_20001,Ballycastle,Ballycastle,55.206280,-6.229273
UKGBNIPA3_20002,Browns Bay,Browns Bay,54.853726,-5.766593
UKGBNIPA3_20004,Ballygalley,Ballygalley,54.899936,-5.857012
UKGBNIPA3_20005,Waterfoot,Waterfoot,55.060553,-6.052456
UKGBNIPA3_20008,Cranfield,Cranfield,54.028437,-6.072754
UKGBNIPA3_20009,Castlerock,Castlerock,55.169385,-6.782202
UKGBNIPA3_20025,Portstewart,Portstewart,55.170108,-6.747745
UKGBNIPA3_20013,Crawfordsburn,Crawfordsburn,54.669594,-5.724275
UKGBNIPA3_20014,Helens Bay,Helens Bay,54.673821,-5.735448
UKGBNIPA3_20015,Groomsport,Groomsport,54.676235,-5.609112
UKGBNIPA3_20016,Ballyholme,Ballyholme,54.667461,-5.643894
UKGBNIPA3_20017,Millisle,Millisle,54.604650,-5.523072
UKGBNIPA3_20018,Ballywalter,Ballywalter,54.538587,-5.481536
UKGBNIPA3_20019,Portrush Mill,Portrush Mill,55.201847,-6.660269
UKGBNIPA3_20020,Tyrella,Tyrella,54.250781,-5.740138
UKGBNIPA3_20003,Carnlough,Carnlough,54.984679,-5.987056
UKGBNIPA3_20023,Magilligan,Magilligan,55.168572,-6.864425
UKGBNIPA3_20022,Downhill,Downhill,55.168068,-6.832230
UKGBNIPA3_20026,Portrush Curran Strand,Portrush Curran Strand,55.207390,-6.638027
UKGBNIPA3_20023,Portrush Whiterocks,Portrush Whiterocks,55.208049,-6.614868
UKGBNIPA3_20006,Newcastle,Newcastle,54.211685,-5.883888
UKGBNIPA3_20024,Murlough,Murlough,54.228560,-5.855003
UKGBNIPA3_20030,Ballyhornan,Ballyhornan,54.304454,-5.549114
UKGBNIPA3_20029,Kilclief,Kilclief,54.332150,-5.541508
UKGBNIPA3_20028,Cloughey,Cloughey,54.431382,-5.471844

In [8]:
locations

,name,alternate_name,lat,long
id,,,,
UKGBNIPA3_20021,Portballintrae Salmon Rock,Portballintrae Salmon Rock,55.220361,-6.543778
UKGBNIPA3_20001,Ballycastle,Ballycastle,55.206280,-6.229273
UKGBNIPA3_20002,Browns Bay,Browns Bay,54.853726,-5.766593
UKGBNIPA3_20004,Ballygalley,Ballygalley,54.899936,-5.857012
UKGBNIPA3_20005,Waterfoot,Waterfoot,55.060553,-6.052456
UKGBNIPA3_20008,Cranfield,Cranfield,54.028437,-6.072754
UKGBNIPA3_20009,Castlerock,Castlerock,55.169385,-6.782202
UKGBNIPA3_20025,Portstewart,Portstewart,55.170108,-6.747745
UKGBNIPA3_20013,Crawfordsburn,Crawfordsburn,54.669594,-5.724275
UKGBNIPA3_20014,Helens Bay,Helens Bay,54.673821,-5.735448
UKGBNIPA3_20015,Groomsport,Groomsport,54.676235,-5.609112
UKGBNIPA3_20016,Ballyholme,Ballyholme,54.667461,-5.643894
UKGBNIPA3_20017,Millisle,Millisle,54.604650,-5.523072
UKGBNIPA3_20018,Ballywalter,Ballywalter,54.538587,-5.481536
UKGBNIPA3_20019,Portrush Mill,Portrush Mill,55.201847,-6.660269
UKGBNIPA3_20020,Tyrella,Tyrella,54.250781,-5.740138
UKGBNIPA3_20003,Carnlough,Carnlough,54.984679,-5.987056
UKGBNIPA3_20023,Magilligan,Magilligan,55.168572,-6.864425
UKGBNIPA3_20022,Downhill,Downhill,55.168068,-6.832230
UKGBNIPA3_20026,Portrush Curran Strand,Portrush Curran Strand,55.207390,-6.638027
UKGBNIPA3_20023,Portrush Whiterocks,Portrush Whiterocks,55.208049,-6.614868
UKGBNIPA3_20006,Newcastle,Newcastle,54.211685,-5.883888
UKGBNIPA3_20024,Murlough,Murlough,54.228560,-5.855003
UKGBNIPA3_20030,Ballyhornan,Ballyhornan,54.304454,-5.549114
UKGBNIPA3_20029,Kilclief,Kilclief,54.332150,-5.541508
UKGBNIPA3_20028,Cloughey,Cloughey,54.431382,-5.471844

In [9]:
db = sqlite3.connect("../dataset.sqlite3")
locations.to_sql("locations", db, if_exists="append")

26